services:
  solr:
    image: solr:9.6.1
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
