---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/search":
    get:
      summary: Searches records
      tags:
      - Search
      parameters:
      - name: keyword
        in: query
        description: Search by keyword
        schema:
          type: string
      - name: page
        in: query
        description: Page of records to return
        schema:
          type: integer
      - name: per_page
        in: query
        description: Max records per page
        schema:
          type: integer
      - name: bbox
        in: query
        description: 'Bounding box to search: west+south+east+north'
        schema:
          type: string
      responses:
        '200':
          description: search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                      required:
                      - id
                      - title
        '406':
          description: unsupported accept header
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
